In [7]:
import numpy as np
array = np.random.randint(25,size=(7,7))
array

array([[13, 15, 10,  6,  9,  6, 13],
       [11,  8, 15,  5,  1, 13, 17],
       [13,  0, 21, 23, 17, 10,  6],
       [16, 14,  4, 24, 17,  6,  8],
       [ 2,  9, 17, 19, 11, 12, 11],
       [ 1,  5,  6, 23,  2, 16,  9],
       [23,  6,  0,  2, 21,  6, 22]])

In [8]:
import numpy as a 
m = a.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
import numpy as c
m=c.array([1,2,3,45])
print(m)
m.dtype

[ 1  2  3 45]


dtype('int32')

In [10]:


import numpy as d
l=d.array([1,2],dtype=complex)
l

array([1.+0.j, 2.+0.j])

In [11]:

import numpy as d
l=d.array([1,2],dtype=complex)
l

array([1.+0.j, 2.+0.j])

In [12]:
import numpy as e
k=e.zeros((3,5))
k

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:

j=e.arange(100,200,5)
print(j)
j=e.arange(2,10,0.3)
j

[100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]


array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3, 5.6,
       5.9, 6.2, 6.5, 6.8, 7.1, 7.4, 7.7, 8. , 8.3, 8.6, 8.9, 9.2, 9.5,
       9.8])

In [15]:
#linspace use to define how much number we want between two given number it will divide them in parts by it self
import numpy as f
i=f.linspace(0,2,8)
i

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

In [16]:
from numpy import pi
x=f.linspace(0,2 * pi,100)
z=f.sin(x)
z

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [17]:

import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(5,29).reshape(2,3,4)

array([[[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28]]])

In [25]:
a=np.array([20,30,40,50,70])
b=np.arange(1,10,2)
c=a-b
d=2*a
print(c)
print(d)
print(b<8)
np.sin(a)

[19 27 35 43 61]
[ 40  60  80 100 140]
[ True  True  True  True False]


array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485,  0.77389068])

In [26]:
import numpy as np
a=np.array([34,23,45,30,10])
b=np.arange(5)
print(b)
print(a)
a*b

[0 1 2 3 4]
[34 23 45 30 10]


array([ 0, 23, 90, 90, 40])

In [27]:
c=np.array([12,3,4,43,34,25,65,26])
c

array([12,  3,  4, 43, 34, 25, 65, 26])

**welcome to python from code with harry**

In [28]:
import numpy as np
myarray=np.array([[3,5,45,35,34,4]],np.int64)
myarray

array([[ 3,  5, 45, 35, 34,  4]], dtype=int64)

In [29]:
myarray.shape

(1, 6)

In [30]:
myarray[0,1]=99 #it changae the value at position [0,1]
myarray

array([[ 3, 99, 45, 35, 34,  4]], dtype=int64)

# array creation:conversion from other python structure

In [31]:
listarray=np.array([[1,3,4],[3,6,3],[0,21,43]])
listarray

array([[ 1,  3,  4],
       [ 3,  6,  3],
       [ 0, 21, 43]])

In [32]:
listarray.dtype

dtype('int32')

In [33]:
listarray.size

9

In [34]:
zeroes=np.zeros([3,4])
zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
m=np.arange(15)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
equal_space=np.linspace(1,50,9)
equal_space

array([ 1.   ,  7.125, 13.25 , 19.375, 25.5  , 31.625, 37.75 , 43.875,
       50.   ])

In [37]:
#empty will generate random value for given size matrix
emp=np.empty([5,6])
emp

array([[1.33240388e-311, 9.58487353e-322, 0.00000000e+000,
        0.00000000e+000, 1.89146896e-307, 1.16097020e-028],
       [4.75385996e-038, 9.72245625e-067, 1.14261192e-071,
        5.01163173e+217, 8.37170074e-144, 2.46580811e+184],
       [3.11411075e-032, 2.12814488e-052, 1.10677955e+165,
        1.06396443e+224, 1.47765135e+248, 4.30625279e-096],
       [9.08366793e+223, 7.11061975e-038, 2.34353737e-056,
        6.02985684e+174, 4.18410836e-062, 1.01849500e+248],
       [1.16096643e-028, 5.30581644e+180, 8.88783102e+252,
        9.30350598e+199, 5.60230216e-067, 6.79764374e-310]])

In [38]:
#emty_like is used to copy above any given matrix
emp_like=np.empty_like(m)
emp_like

array([      0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,    1364,       0,       0, 1733376,
             0])

In [40]:
ide=np.identity(6)
ide

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [41]:
ide.shape

(6, 6)

In [42]:
arr=np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
arr=arr.reshape(4,25)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
arr=np.arange(100).reshape(4,25)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [47]:
#ravel will create 1 d array by creating all aray in single list(2d array into 1 d array)
#converting 2d array into 1d array
arr=arr.ravel()#ravel
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [48]:
arr.shape

(100,)

**numpy axis**

In [49]:
x=[[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
#axis 0 is alll element of particular colum in 2 d array (which is downside )
#axis 1 is alll element of particular row in 2 d array (which is on sideway direction )
ar.sum(axis=0)#it will make sum  of all column 

array([12, 15, 18])

In [51]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [58]:
z=ar.T
z
#ar.T is used to transpose the matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
ar.flat

In [54]:
for item in ar.flat:
    print (item)

1
2
3
4
5
6
7
8
9


In [55]:
ar.ndim  #it will show dimension 

2

In [56]:
ar.size

9

In [57]:
ar.nbytes

36

In [59]:
one=np.array([1,43,35,2,453,34])
i=one.argmax()#it will give maximum element position,,/*one.argmax
c=one.argmin()#it will give minimum element position
d=one.argsort()#it will show your position of  index, must be so your array will be sort
print(i)
print(c)

4
0


In [60]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
arr.argmax()

8

In [62]:
arr.argmin()

0

In [63]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [64]:
arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [66]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [67]:
arr.reshape((9,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [70]:
z=arr.ravel()
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
ar2=np.array([[2,3,1],[4,5,3],[6,1,5]])
ar2

array([[2, 3, 1],
       [4, 5, 3],
       [6, 1, 5]])

In [72]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
ar+ar2

array([[ 3,  5,  4],
       [ 8, 10,  9],
       [13,  9, 14]])

In [74]:
ar*ar2

array([[ 2,  6,  3],
       [16, 25, 18],
       [42,  8, 45]])

In [75]:
np.sqrt(ar2)

array([[1.41421356, 1.73205081, 1.        ],
       [2.        , 2.23606798, 1.73205081],
       [2.44948974, 1.        , 2.23606798]])

In [76]:
ar.sum()

45

In [77]:
ar.min()

1

In [78]:
ar.max()

9

In [79]:
arm=np.array([[2,4,5],[7,3,2],[9,7,1]])
arm
np.where(arm > 5)

(array([1, 2, 2], dtype=int64), array([0, 0, 1], dtype=int64))

In [80]:
ar2

array([[2, 3, 1],
       [4, 5, 3],
       [6, 1, 5]])

In [81]:
np.nonzero(ar2)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [82]:
np.count_nonzero(ar2)

9

In [83]:
import sys
py_ar=[0,12,34,23,23]
np_ar=np.array(py_ar)
sys.getsizeof(1)*len(py_ar)

140

In [84]:
np_ar.itemsize*np_ar.size

20

In [85]:
arr@ar# @ is used for multiplication of the matrix//multiplication

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

# revision (from documentation)

In [86]:
from numpy import pi
pi

3.141592653589793

In [87]:
b=np.linspace(0,pi,3)
b

array([0.        , 1.57079633, 3.14159265])

In [88]:
b.sum()

4.71238898038469

In [89]:
b.min()

0.0

In [90]:
c=np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
c.cumsum(axis=1)#cumsum is used for summing up cumulative sum along each rows and column

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [92]:
d=np.random.randint(12,size=(3,4))
d

array([[ 0,  8,  9, 10],
       [ 8,  0, 10,  0],
       [ 8,  6,  9,  5]])

In [93]:
np.add(c,d)

array([[ 0,  9, 11, 13],
       [12,  5, 16,  7],
       [16, 15, 19, 16]])

In [94]:
c[1,1]=0
c

array([[ 0,  1,  2,  3],
       [ 4,  0,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
c[:2:4]=10 ##not understood
c

array([[10, 10, 10, 10],
       [ 4,  0,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
c

array([[10, 10, 10, 10],
       [ 4,  0,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
d[::-1] ## this used for reversing the value (matrix)

array([[ 8,  6,  9,  5],
       [ 8,  0, 10,  0],
       [ 0,  8,  9, 10]])

In [101]:
#d.ravel()
print(d)
for item in d:
    print (item ,"\n")####doubt

[[ 0  8  9 10]
 [ 8  0 10  0]
 [ 8  6  9  5]]
[ 0  8  9 10] 

[ 8  0 10  0] 

[8 6 9 5] 



In [102]:
############function in numpy##########


In [103]:
def f(x,y):
    return 10*x+y
b=np.fromfunction(f,(3,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

**below is for printing particular row or column **

In [104]:
b[0:3,1]

array([ 1, 11, 21])

In [105]:
b[1:2,1]

array([11])

In [106]:
b[0:3,3]

array([ 3, 13, 23])

In [107]:
b[1,0:4]

array([10, 11, 12, 13])

In [108]:
e=np.random.randint(12,size=(2,2,3))#3d array here with 2 stacked 2d array
e

array([[[10,  6,  7],
        [ 8,  4, 11]],

       [[ 0,  0,  2],
        [ 5,  5,  9]]])

In [109]:

e.shape

(2, 2, 3)

In [110]:
e[1,...]

array([[0, 0, 2],
       [5, 5, 9]])

In [111]:
for row in e :
    print (row)

[[10  6  7]
 [ 8  4 11]]
[[0 0 2]
 [5 5 9]]


In [112]:
for j in e.flat:##flat is used to print 1 element in 1 line
    print(j)

10
6
7
8
4
11
0
0
2
5
5
9


In [113]:


##modifying the shape ############
e.ravel()


array([10,  6,  7,  8,  4, 11,  0,  0,  2,  5,  5,  9])

In [114]:
e.reshape(4,3)

array([[10,  6,  7],
       [ 8,  4, 11],
       [ 0,  0,  2],
       [ 5,  5,  9]])

In [115]:
e.T

array([[[10,  0],
        [ 8,  5]],

       [[ 6,  0],
        [ 4,  5]],

       [[ 7,  2],
        [11,  9]]])

In [116]:
e.resize((2,6))
e

array([[10,  6,  7,  8,  4, 11],
       [ 0,  0,  2,  5,  5,  9]])

In [117]:
e.reshape(3,-1)#a dimension is given as -1 in a reshaping operation,
                #the other dimensions are automatically calculated

array([[10,  6,  7,  8],
       [ 4, 11,  0,  0],
       [ 2,  5,  5,  9]])

**stacking together different arrays**


In [118]:
import numpy as np
rg= np.random.default_rng(1)#this is also one of the method to generate 
#random number but below method is more easier
a=np.floor( 100 *rg.random((2,2)))
a

array([[51., 95.],
       [14., 94.]])

In [119]:
b=np.floor(np.random.randint(100,size=(2,2)))
b

array([[90., 96.],
       [10., 82.]])

In [120]:
#vertical stack
np.vstack((a,b))

array([[51., 95.],
       [14., 94.],
       [90., 96.],
       [10., 82.]])

In [121]:
#horizontal stack
np.hstack((a,b))

array([[51., 95., 90., 96.],
       [14., 94., 10., 82.]])

In [122]:
#column stack :stacks 1 d arrays as column in to a 2d array 
#(for 2 or more than two 1 d array)


In [123]:




a=np.linspace(1,25,5)
print(a)
b=np.linspace(1,37,5)
print(b)

[ 1.  7. 13. 19. 25.]
[ 1. 10. 19. 28. 37.]


In [124]:



from numpy import newaxis
np.column_stack((a,b))

array([[ 1.,  1.],
       [ 7., 10.],
       [13., 19.],
       [19., 28.],
       [25., 37.]])

In [125]:
np.vstack((a,b))

array([[ 1.,  7., 13., 19., 25.],
       [ 1., 10., 19., 28., 37.]])

In [126]:
np.row_stack((a,b))

array([[ 1.,  7., 13., 19., 25.],
       [ 1., 10., 19., 28., 37.]])

In [127]:
np.row_stack is np.vstack


True

In [128]:
np.column_stack is np.hstack

False

# splitting one array into several smaller ones

In [129]:
a=np.floor(np.random.randint(12,size=(2,12)))
a

array([[ 7.,  2.,  7.,  3.,  7.,  6.,  2.,  3.,  5.,  9.,  4.,  1.],
       [ 7.,  7.,  4.,  7.,  7.,  5.,  6.,  2.,  7., 10.,  0.,  5.]])

In [130]:
np.hsplit(a,)

TypeError: _hvdsplit_dispatcher() missing 1 required positional argument: 'indices_or_sections'

In [131]:
np.hsplit(a,(3,5))#used for spliting in different dimension
# np.hsplit(a,(3,5))#it will 1st split till 3rd column then it will split 
                  #4th and 5th and then  split rest all

[array([[7., 2., 7.],
        [7., 7., 4.]]),
 array([[3., 7.],
        [7., 7.]]),
 array([[ 6.,  2.,  3.,  5.,  9.,  4.,  1.],
        [ 5.,  6.,  2.,  7., 10.,  0.,  5.]])]

In [132]:
a=np.floor(np.random.randint(12,size=(4,3)))
a

array([[ 4.,  2., 10.],
       [ 9.,  3.,  9.],
       [ 7.,  1., 10.],
       [ 2., 11.,  3.]])

**#concept of copy in python##**

In [133]:









#Python passes mutable objects as references,so function calls make no copy
b=a    # no new object is created
b is a # a and b are two names for the same ndarray object
True
b is a

True

In [134]:
c=a.view()
c is a

False

In [135]:
c.base is a # c is a view of the data owned by a
c=c.reshape((2,6))
a.shape  #a's shape does not change

(4, 3)

In [136]:
c[0,4]=1232
a  #a's data change

array([[4.000e+00, 2.000e+00, 1.000e+01],
       [9.000e+00, 1.232e+03, 9.000e+00],
       [7.000e+00, 1.000e+00, 1.000e+01],
       [2.000e+00, 1.100e+01, 3.000e+00]])

In [137]:
s=a[:,1:3]
s[:]=10
a

array([[ 4., 10., 10.],
       [ 9., 10., 10.],
       [ 7., 10., 10.],
       [ 2., 10., 10.]])

In [138]:
#best for copying item 
d=a.copy()
# a new array object with new data is created
d is a #d has copy of a but they are not eqal

False

In [139]:
d.base is a
#d doesn't share anything with a 

False

In [140]:
d[0,0]=1111
a#it does not make any changes on a

array([[ 4., 10., 10.],
       [ 9., 10., 10.],
       [ 7., 10., 10.],
       [ 2., 10., 10.]])

In [141]:
d

array([[1111.,   10.,   10.],
       [   9.,   10.,   10.],
       [   7.,   10.,   10.],
       [   2.,   10.,   10.]])

In [142]:


v=np.zeros_like(d)
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# advance indexing and index tricks

In [143]:
a=np.arange(12)**2 #used to print sqare of first 12 integer
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [144]:
i=np.array([1,11,3,8,5])
a[i]

array([  1, 121,   9,  64,  25], dtype=int32)

In [145]:
#printing array using indexing
import numpy as np
p=np.array([[0,0,0],
           [255,0,0],
           [0,255,0],
           [0,0,255],
           [255,255,255]])
image=np.array([[0,1,2,0],#this are index
              [0,3,4,0] ])
p[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

**doubt(cleared)**

In [146]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:












i=np.array([[0,1],
            [1,2]])
j=np.array([[2,1],
            [3,3]])
a[i,j]#it will print a(i,j ) element 
#a(0,2),a(1,1)...

array([[ 2,  5],
       [ 7, 11]])

In [148]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [149]:
a[:,j]#it will take all element of row one by one row sequence

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [150]:
time=np.linspace(20,145,5)
data=np.sin(np.arange(20)).reshape(5,4)
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [151]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [152]:
m=data.argmax(axis=0)
m

array([2, 0, 3, 1], dtype=int64)

In [153]:
n=data.argmin(axis=1)
n

array([0, 1, 3, 0, 1], dtype=int64)

In [154]:
data_max

NameError: name 'data_max' is not defined

In [155]:
import numpy as np 
a=np.arange(5)
a[[0,0,2]]=[1,2,3]
a

array([2, 1, 3, 3, 4])

In [156]:
a[[0,1,2]]+=1
a

array([3, 2, 4, 3, 4])

**indexing with boolean arrays**

In [157]:
import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
b=a>4
print(b)
print(a[b])
a[b]=0#it will make all element 0 which are grreater than
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]


In [158]:
a=np.array([2,3,4,5])
b=np.array([8,5,4])
c=np.array([5,4,6,8,3])
ax,bx,cx=np.ix_(a,b,c)
print(ax)
print(bx)
print(cx)

[[[2]]

 [[3]]

 [[4]]

 [[5]]]
[[[8]
  [5]
  [4]]]
[[[5 4 6 8 3]]]


In [159]:
result=ax+bx+cx
result

array([[[15, 14, 16, 18, 13],
        [12, 11, 13, 15, 10],
        [11, 10, 12, 14,  9]],

       [[16, 15, 17, 19, 14],
        [13, 12, 14, 16, 11],
        [12, 11, 13, 15, 10]],

       [[17, 16, 18, 20, 15],
        [14, 13, 15, 17, 12],
        [13, 12, 14, 16, 11]],

       [[18, 17, 19, 21, 16],
        [15, 14, 16, 18, 13],
        [14, 13, 15, 17, 12]]])

In [160]:
ax.shape,bx.shape,cx.shape

((4, 1, 1), (1, 3, 1), (1, 1, 5))

In [161]:
ax+bx*cx

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

In [162]:
a=np.arange(30)
b=a.reshape(2,-1,3)
b.shape

(2, 5, 3)

In [163]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [164]:
x=np.arange(0,10,2)
y=np.arange(5)
m=np.vstack([x,y])
m

array([[0, 2, 4, 6, 8],
       [0, 1, 2, 3, 4]])

In [165]:
n=np.hstack([x,y])
n

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])