In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('M:/sem 5/de/titles.csv')

In [3]:
dataset.head()

id                                title   type  \
0  ts300399  Five Came Back: The Reference Films   SHOW   
1   tm84618                          Taxi Driver  MOVIE   
2  tm127384      Monty Python and the Holy Grail  MOVIE   
3   tm70993                        Life of Brian  MOVIE   
4  tm190788                         The Exorcist  MOVIE   

                                         description  release_year  \
0  This collection includes 12 World War II-era p...          1945   
1  A mentally unstable Vietnam War veteran works ...          1976   
2  King Arthur, accompanied by his squire, recrui...          1975   
3  Brian Cohen is an average young Jewish man, bu...          1979   
4  12-year-old Regan MacNeil begins to adapt an e...          1973   

  age_certification  runtime                 genres production_countries  \
0             TV-MA       48      ['documentation']               ['US']   
1                 R      113     ['crime', 'drama']               ['US']   
2                PG       91  ['comedy', 'fantasy']               ['GB']   
3                 R       94             ['comedy']               ['GB']   
4                 R      133             ['horror']               ['US']   

   seasons    imdb_id  imdb_score  imdb_votes  tmdb_popularity  tmdb_score  
0      1.0        NaN         NaN         NaN            0.600         NaN  
1      NaN  tt0075314         8.3    795222.0           27.612         8.2  
2      NaN  tt0071853         8.2    530877.0           18.216         7.8  
3      NaN  tt0079470         8.0    392419.0           17.505         7.8  
4      NaN  tt0070047         8.1    391942.0           95.337         7.7

In [4]:
dataset=dataset.drop(columns='seasons')

In [5]:
dataset=dataset.drop(columns='description')

In [6]:
dataset=dataset.drop(columns='imdb_id')

In [7]:
dataset=dataset.drop(columns='id')

In [8]:
dataset

title   type  release_year  \
0     Five Came Back: The Reference Films   SHOW          1945   
1                             Taxi Driver  MOVIE          1976   
2         Monty Python and the Holy Grail  MOVIE          1975   
3                           Life of Brian  MOVIE          1979   
4                            The Exorcist  MOVIE          1973   
...                                   ...    ...           ...   
5801                            Fine Wine  MOVIE          2021   
5802                       Edis Starlight  MOVIE          2021   
5803                                Clash  MOVIE          2021   
5804                       Shadow Parties  MOVIE          2021   
5805   Mighty Little Bheem: Kite Festival   SHOW          2021   

     age_certification  runtime                             genres  \
0                TV-MA       48                  ['documentation']   
1                    R      113                 ['crime', 'drama']   
2                   PG       91              ['comedy', 'fantasy']   
3                    R       94                         ['comedy']   
4                    R      133                         ['horror']   
...                ...      ...                                ...   
5801               NaN      100               ['romance', 'drama']   
5802               NaN       74         ['music', 'documentation']   
5803               NaN       88                ['family', 'drama']   
5804               NaN      116             ['action', 'thriller']   
5805               NaN        0  ['family', 'comedy', 'animation']   

     production_countries  imdb_score  imdb_votes  tmdb_popularity  tmdb_score  
0                  ['US']         NaN         NaN            0.600         NaN  
1                  ['US']         8.3    795222.0           27.612         8.2  
2                  ['GB']         8.2    530877.0           18.216         7.8  
3                  ['GB']         8.0    392419.0           17.505         7.8  
4                  ['US']         8.1    391942.0           95.337         7.7  
...                   ...         ...         ...              ...         ...  
5801               ['NG']         6.9        39.0            0.966         NaN  
5802                   []         NaN         NaN            1.036         8.5  
5803         ['NG', 'CA']         6.5        32.0            0.709         NaN  
5804                   []         6.2         9.0            2.186         NaN  
5805                   []         8.8        16.0            0.979        10.0  

[5806 rows x 11 columns]

In [9]:
dataset=dataset.replace(to_replace="[]",value=np.nan)



In [10]:
x=dataset.drop(columns=['runtime','imdb_score','tmdb_score','imdb_votes','tmdb_popularity'],axis=1).copy()
x



title   type  release_year  \
0     Five Came Back: The Reference Films   SHOW          1945   
1                             Taxi Driver  MOVIE          1976   
2         Monty Python and the Holy Grail  MOVIE          1975   
3                           Life of Brian  MOVIE          1979   
4                            The Exorcist  MOVIE          1973   
...                                   ...    ...           ...   
5801                            Fine Wine  MOVIE          2021   
5802                       Edis Starlight  MOVIE          2021   
5803                                Clash  MOVIE          2021   
5804                       Shadow Parties  MOVIE          2021   
5805   Mighty Little Bheem: Kite Festival   SHOW          2021   

     age_certification                             genres production_countries  
0                TV-MA                  ['documentation']               ['US']  
1                    R                 ['crime', 'drama']               ['US']  
2                   PG              ['comedy', 'fantasy']               ['GB']  
3                    R                         ['comedy']               ['GB']  
4                    R                         ['horror']               ['US']  
...                ...                                ...                  ...  
5801               NaN               ['romance', 'drama']               ['NG']  
5802               NaN         ['music', 'documentation']                  NaN  
5803               NaN                ['family', 'drama']         ['NG', 'CA']  
5804               NaN             ['action', 'thriller']                  NaN  
5805               NaN  ['family', 'comedy', 'animation']                  NaN  

[5806 rows x 6 columns]

In [11]:
x_list=['runtime','imdb_votes','tmdb_popularity','tmdb_score']


In [12]:
x_numeric=dataset[x_list]
x_numeric.head()

runtime  imdb_votes  tmdb_popularity  tmdb_score
0       48         NaN            0.600         NaN
1      113    795222.0           27.612         8.2
2       91    530877.0           18.216         7.8
3       94    392419.0           17.505         7.8
4      133    391942.0           95.337         7.7

In [13]:
x_numeric=x_numeric.values
x_numeric

array([[4.80000e+01,         nan, 6.00000e-01,         nan],
       [1.13000e+02, 7.95222e+05, 2.76120e+01, 8.20000e+00],
       [9.10000e+01, 5.30877e+05, 1.82160e+01, 7.80000e+00],
       ...,
       [8.80000e+01, 3.20000e+01, 7.09000e-01,         nan],
       [1.16000e+02, 9.00000e+00, 2.18600e+00,         nan],
       [0.00000e+00, 1.60000e+01, 9.79000e-01, 1.00000e+01]])

In [14]:
y=dataset['imdb_score'].copy()
y=y.replace(to_replace=np.nan,value=5.5)

In [15]:
y.shape

(5806,)

In [16]:
y=y.values

In [17]:
x=x.values

In [18]:
print(x)

[['Five Came Back: The Reference Films' 'SHOW' 1945 'TV-MA'
  "['documentation']" "['US']"]
 ['Taxi Driver' 'MOVIE' 1976 'R' "['crime', 'drama']" "['US']"]
 ['Monty Python and the Holy Grail' 'MOVIE' 1975 'PG'
  "['comedy', 'fantasy']" "['GB']"]
 ...
 ['Clash' 'MOVIE' 2021 nan "['family', 'drama']" "['NG', 'CA']"]
 ['Shadow Parties' 'MOVIE' 2021 nan "['action', 'thriller']" nan]
 ['Mighty Little Bheem: Kite Festival' 'SHOW' 2021 nan
  "['family', 'comedy', 'animation']" nan]]


In [19]:
x.shape

(5806, 6)

In [20]:
print(y)

[5.5 8.3 8.2 ... 6.5 6.2 8.8]


In [21]:
y.size

5806

# data preprocessing of numerical data

In [22]:
x.reshape(-1,1)

array([['Five Came Back: The Reference Films'],
       ['SHOW'],
       [1945],
       ...,
       [nan],
       ["['family', 'comedy', 'animation']"],
       [nan]], dtype=object)

In [23]:
x

array([['Five Came Back: The Reference Films', 'SHOW', 1945, 'TV-MA',
        "['documentation']", "['US']"],
       ['Taxi Driver', 'MOVIE', 1976, 'R', "['crime', 'drama']",
        "['US']"],
       ['Monty Python and the Holy Grail', 'MOVIE', 1975, 'PG',
        "['comedy', 'fantasy']", "['GB']"],
       ...,
       ['Clash', 'MOVIE', 2021, nan, "['family', 'drama']",
        "['NG', 'CA']"],
       ['Shadow Parties', 'MOVIE', 2021, nan, "['action', 'thriller']",
        nan],
       ['Mighty Little Bheem: Kite Festival', 'SHOW', 2021, nan,
        "['family', 'comedy', 'animation']", nan]], dtype=object)

In [24]:
from sklearn.impute import SimpleImputer 

In [25]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')


In [26]:
imputer.fit(x_numeric[:,1:])

SimpleImputer()

In [27]:
x_numeric[:,1:]=imputer.transform(x_numeric[:,1:])

In [28]:
x_numeric[:,1:]

array([[2.34071950e+04, 6.00000000e-01, 6.81803936e+00],
       [7.95222000e+05, 2.76120000e+01, 8.20000000e+00],
       [5.30877000e+05, 1.82160000e+01, 7.80000000e+00],
       ...,
       [3.20000000e+01, 7.09000000e-01, 6.81803936e+00],
       [9.00000000e+00, 2.18600000e+00, 6.81803936e+00],
       [1.60000000e+01, 9.79000000e-01, 1.00000000e+01]])

In [29]:
X=x_numeric.copy()
X

array([[4.80000000e+01, 2.34071950e+04, 6.00000000e-01, 6.81803936e+00],
       [1.13000000e+02, 7.95222000e+05, 2.76120000e+01, 8.20000000e+00],
       [9.10000000e+01, 5.30877000e+05, 1.82160000e+01, 7.80000000e+00],
       ...,
       [8.80000000e+01, 3.20000000e+01, 7.09000000e-01, 6.81803936e+00],
       [1.16000000e+02, 9.00000000e+00, 2.18600000e+00, 6.81803936e+00],
       [0.00000000e+00, 1.60000000e+01, 9.79000000e-01, 1.00000000e+01]])

In [30]:
x

array([['Five Came Back: The Reference Films', 'SHOW', 1945, 'TV-MA',
        "['documentation']", "['US']"],
       ['Taxi Driver', 'MOVIE', 1976, 'R', "['crime', 'drama']",
        "['US']"],
       ['Monty Python and the Holy Grail', 'MOVIE', 1975, 'PG',
        "['comedy', 'fantasy']", "['GB']"],
       ...,
       ['Clash', 'MOVIE', 2021, nan, "['family', 'drama']",
        "['NG', 'CA']"],
       ['Shadow Parties', 'MOVIE', 2021, nan, "['action', 'thriller']",
        nan],
       ['Mighty Little Bheem: Kite Festival', 'SHOW', 2021, nan,
        "['family', 'comedy', 'animation']", nan]], dtype=object)

# data preprocessing of string data

In [31]:
imp=SimpleImputer(missing_values=np.nan,strategy="most_frequent")

In [32]:
imp.fit(x[:,1:])

SimpleImputer(strategy='most_frequent')

In [33]:
x[:,1:]=imp.transform(x[:,1:])

In [34]:
x[:,1:]

array([['SHOW', 1945, 'TV-MA', "['documentation']", "['US']"],
       ['MOVIE', 1976, 'R', "['crime', 'drama']", "['US']"],
       ['MOVIE', 1975, 'PG', "['comedy', 'fantasy']", "['GB']"],
       ...,
       ['MOVIE', 2021, 'TV-MA', "['family', 'drama']", "['NG', 'CA']"],
       ['MOVIE', 2021, 'TV-MA', "['action', 'thriller']", "['US']"],
       ['SHOW', 2021, 'TV-MA', "['family', 'comedy', 'animation']",
        "['US']"]], dtype=object)

In [35]:
X.shape

(5806, 4)

In [36]:
x.shape

(5806, 6)

In [37]:
final=np.concatenate((x,X),axis=1)

In [38]:
final

array([['Five Came Back: The Reference Films', 'SHOW', 1945, ...,
        23407.194987659008, 0.6, 6.818039358600582],
       ['Taxi Driver', 'MOVIE', 1976, ..., 795222.0, 27.612, 8.2],
       ['Monty Python and the Holy Grail', 'MOVIE', 1975, ..., 530877.0,
        18.216, 7.8],
       ...,
       ['Clash', 'MOVIE', 2021, ..., 32.0, 0.709, 6.818039358600582],
       ['Shadow Parties', 'MOVIE', 2021, ..., 9.0, 2.186,
        6.818039358600582],
       ['Mighty Little Bheem: Kite Festival', 'SHOW', 2021, ..., 16.0,
        0.979, 10.0]], dtype=object)

In [39]:
final[120:121,:]

array([['Neon Genesis Evangelion', 'SHOW', 1995, 'TV-14',
        "['scifi', 'action', 'drama', 'thriller', 'fantasy', 'animation']",
        "['JP']", 24.0, 64727.0, 51.993, 8.6]], dtype=object)

In [40]:
y.size

5806

# preprocessing of lable(predicted data)

In [41]:
#y=y.reshape(1,-1)

In [42]:
#y.size

In [43]:
#y

In [44]:
#imp=SimpleImputer(missing_values=np.nan,strategy="most_frequent")

In [45]:
#imp.fit(y)

In [46]:
#y=imp.transform(y)

In [47]:
#y

In [48]:
#y.size

# lable _ encoding

In [49]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()#creating object
le2=LabelEncoder()#creating object
le3=LabelEncoder()#creating object
le4=LabelEncoder()#creating object
le5=LabelEncoder()#creating object
le6=LabelEncoder()#creating object
final[:,0]=le1.fit_transform(final[:,1])
final[:,1]=le2.fit_transform(final[:,1])
final[:,3]=le3.fit_transform(final[:,1])
final[:,4]=le4.fit_transform(final[:,1])
final[:,5]=le5.fit_transform(final[:,1])
y=le6.fit_transform(y)


In [50]:
print(final)

[[1 1 1945 ... 23407.194987659008 0.6 6.818039358600582]
 [0 0 1976 ... 795222.0 27.612 8.2]
 [0 0 1975 ... 530877.0 18.216 7.8]
 ...
 [0 0 2021 ... 32.0 0.709 6.818039358600582]
 [0 0 2021 ... 9.0 2.186 6.818039358600582]
 [1 1 2021 ... 16.0 0.979 10.0]]


In [51]:
print(y)

[40 68 67 ... 50 47 73]


In [52]:
y=y.astype(int)

In [53]:
y

array([40, 68, 67, ..., 50, 47, 73])

In [54]:
final.shape

(5806, 10)

In [55]:
y.shape

(5806,)

# spliting dataset into training and testing set

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
final_train,final_test,y_train,y_test=train_test_split(final,y,test_size=0.2,random_state=0)

In [58]:
# print(final_train)

In [59]:
print(final_test)

[[1 1 2016 ... 1769.0 22.672 8.2]
 [1 1 2021 ... 14040.0 21.349 7.3]
 [0 0 2012 ... 286.0 2.552 4.9]
 ...
 [0 0 2021 ... 804.0 7.246 8.1]
 [0 0 2019 ... 23407.194987659008 2.218 6.8]
 [1 1 2017 ... 2168.0 11.357 7.3]]


In [60]:
print(y_train)

[36 51 48 ... 57 44 51]


In [61]:
print(y_test)

[64 60 37 ... 49 40 51]


# feature scaling

In [62]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
final_train=sc.fit_transform(final_train)
final_test=sc.fit_transform(final_test)

In [63]:
final_train

array([[-0.73644059, -0.73644059,  0.27378269, ..., -0.18921012,
        -0.2038601 , -1.68221085],
       [ 1.35788279,  1.35788279,  0.82211555, ..., -0.27414938,
         0.0076324 , -0.0962011 ],
       [ 1.35788279,  1.35788279,  0.41086591, ..., -0.25979247,
         0.13016947,  1.13736204],
       ...,
       [-0.73644059, -0.73644059, -0.13746695, ...,  0.01214856,
        -0.23088065,  0.34435717],
       [-0.73644059, -0.73644059,  0.13669948, ..., -0.2528708 ,
        -0.22581338, -0.44864771],
       [-0.73644059, -0.73644059,  0.13669948, ..., -0.27444119,
        -0.32127132,  1.04925039]])

In [64]:
final_test

array([[ 1.34415895,  1.34415895, -0.00751806, ..., -0.29102737,
         0.00279766,  1.1667827 ],
       [ 1.34415895,  1.34415895,  0.66448065, ..., -0.11873031,
        -0.01657492,  0.38693886],
       [-0.74395963, -0.74395963, -0.54511703, ..., -0.31185016,
        -0.29181792, -1.69264473],
       ...,
       [-0.74395963, -0.74395963,  0.66448065, ..., -0.30457693,
        -0.22308405,  1.08013339],
       [-0.74395963, -0.74395963,  0.39568117, ...,  0.01279444,
        -0.29670866, -0.04630772],
       [ 1.34415895,  1.34415895,  0.12688168, ..., -0.28542501,
        -0.162887  ,  0.38693886]])

# training dataset

In [66]:
from xgboost import XGBClassifier 
model=XGBClassifier()
model.fit(final_train,y_train[:-1])

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79], got [ 0  1  2  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80]